// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: commit_virtual_psbt.sql

package sqlc

import (
	"context"
)

const DeleteCommitVirtualPsbt = `-- name: DeleteCommitVirtualPsbt :exec
DELETE FROM commit_virtual_psbt_idem
WHERE request_id = $1
`

func (q *Queries) DeleteCommitVirtualPsbt(ctx context.Context, requestID []byte) error {
	_, err := q.db.ExecContext(ctx, DeleteCommitVirtualPsbt, requestID)
	return err
}

const FetchCommitVirtualPsbt = `-- name: FetchCommitVirtualPsbt :one
SELECT record
FROM commit_virtual_psbt_idem
WHERE request_id = $1
`

func (q *Queries) FetchCommitVirtualPsbt(ctx context.Context, requestID []byte) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, FetchCommitVirtualPsbt, requestID)
	var record []byte
	err := row.Scan(&record)
	return record, err
}

const InsertCommitVirtualPsbt = `-- name: InsertCommitVirtualPsbt :exec
INSERT INTO commit_virtual_psbt_idem (
    request_id, record
) VALUES (
    $1, $2
)
`

type InsertCommitVirtualPsbtParams struct {
	RequestID []byte
	Record    []byte
}

func (q *Queries) InsertCommitVirtualPsbt(ctx context.Context, arg InsertCommitVirtualPsbtParams) error {
	_, err := q.db.ExecContext(ctx, InsertCommitVirtualPsbt, arg.RequestID, arg.Record)
	return err
}

const UpdateCommitVirtualPsbt = `-- name: UpdateCommitVirtualPsbt :execrows
UPDATE commit_virtual_psbt_idem
SET record = $2
WHERE request_id = $1
`

type UpdateCommitVirtualPsbtParams struct {
	RequestID []byte
	Record    []byte
}

func (q *Queries) UpdateCommitVirtualPsbt(ctx context.Context, arg UpdateCommitVirtualPsbtParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, UpdateCommitVirtualPsbt, arg.RequestID, arg.Record)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
