// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: commit_virtual_psbt.sql

package sqlc

import (
	"context"
	"database/sql"
)

const DeleteCommitVirtualPsbt = `-- name: DeleteCommitVirtualPsbt :exec
DELETE FROM commit_virtual_psbt_idem
WHERE request_id = $1
`

func (q *Queries) DeleteCommitVirtualPsbt(ctx context.Context, requestID []byte) error {
	_, err := q.db.ExecContext(ctx, DeleteCommitVirtualPsbt, requestID)
	return err
}

const DeleteCommitVirtualPsbtIf = `-- name: DeleteCommitVirtualPsbtIf :execrows
DELETE FROM commit_virtual_psbt_idem
WHERE request_id = $1
  AND record = $2
`

type DeleteCommitVirtualPsbtIfParams struct {
	RequestID      []byte
	ExpectedRecord []byte
}

func (q *Queries) DeleteCommitVirtualPsbtIf(ctx context.Context, arg DeleteCommitVirtualPsbtIfParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, DeleteCommitVirtualPsbtIf, arg.RequestID, arg.ExpectedRecord)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const FetchCommitVirtualPsbt = `-- name: FetchCommitVirtualPsbt :one
SELECT record
FROM commit_virtual_psbt_idem
WHERE request_id = $1
`

func (q *Queries) FetchCommitVirtualPsbt(ctx context.Context, requestID []byte) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, FetchCommitVirtualPsbt, requestID)
	var record []byte
	err := row.Scan(&record)
	return record, err
}

const InsertCommitVirtualPsbt = `-- name: InsertCommitVirtualPsbt :exec
INSERT INTO commit_virtual_psbt_idem (
    request_id, record
) VALUES (
    $1, $2
)
`

type InsertCommitVirtualPsbtParams struct {
	RequestID []byte
	Record    []byte
}

func (q *Queries) InsertCommitVirtualPsbt(ctx context.Context, arg InsertCommitVirtualPsbtParams) error {
	_, err := q.db.ExecContext(ctx, InsertCommitVirtualPsbt, arg.RequestID, arg.Record)
	return err
}

const ListCommitVirtualPsbts = `-- name: ListCommitVirtualPsbts :many
SELECT request_id, record
FROM commit_virtual_psbt_idem
`

type ListCommitVirtualPsbtsRow struct {
	RequestID []byte
	Record    []byte
}

func (q *Queries) ListCommitVirtualPsbts(ctx context.Context) ([]ListCommitVirtualPsbtsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListCommitVirtualPsbts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommitVirtualPsbtsRow
	for rows.Next() {
		var i ListCommitVirtualPsbtsRow
		if err := rows.Scan(&i.RequestID, &i.Record); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListUnstampedCommitVirtualPsbts = `-- name: ListUnstampedCommitVirtualPsbts :many
SELECT request_id, record
FROM commit_virtual_psbt_idem
WHERE finished_at IS NULL
`

type ListUnstampedCommitVirtualPsbtsRow struct {
	RequestID []byte
	Record    []byte
}

func (q *Queries) ListUnstampedCommitVirtualPsbts(ctx context.Context) ([]ListUnstampedCommitVirtualPsbtsRow, error) {
	rows, err := q.db.QueryContext(ctx, ListUnstampedCommitVirtualPsbts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnstampedCommitVirtualPsbtsRow
	for rows.Next() {
		var i ListUnstampedCommitVirtualPsbtsRow
		if err := rows.Scan(&i.RequestID, &i.Record); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const PurgeFinishedCommitVirtualPsbts = `-- name: PurgeFinishedCommitVirtualPsbts :execrows
DELETE FROM commit_virtual_psbt_idem
WHERE finished_at IS NOT NULL
  AND finished_at < $1
`

func (q *Queries) PurgeFinishedCommitVirtualPsbts(ctx context.Context, finishedBefore sql.NullTime) (int64, error) {
	result, err := q.db.ExecContext(ctx, PurgeFinishedCommitVirtualPsbts, finishedBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const SwapCommitVirtualPsbt = `-- name: SwapCommitVirtualPsbt :execrows
UPDATE commit_virtual_psbt_idem
SET record = $1,
    finished_at = COALESCE($2, finished_at)
WHERE request_id = $3
  AND record = $4
`

type SwapCommitVirtualPsbtParams struct {
	NextRecord     []byte
	FinishedAt     sql.NullTime
	RequestID      []byte
	ExpectedRecord []byte
}

func (q *Queries) SwapCommitVirtualPsbt(ctx context.Context, arg SwapCommitVirtualPsbtParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, SwapCommitVirtualPsbt,
		arg.NextRecord,
		arg.FinishedAt,
		arg.RequestID,
		arg.ExpectedRecord,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const UpdateCommitVirtualPsbt = `-- name: UpdateCommitVirtualPsbt :execrows
UPDATE commit_virtual_psbt_idem
SET record = $2
WHERE request_id = $1
`

type UpdateCommitVirtualPsbtParams struct {
	RequestID []byte
	Record    []byte
}

func (q *Queries) UpdateCommitVirtualPsbt(ctx context.Context, arg UpdateCommitVirtualPsbtParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, UpdateCommitVirtualPsbt, arg.RequestID, arg.Record)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
